#!/bin/bash

export IMAGE=$(sed -n '1p' /tmp/.auth)
export TAG=$(sed -n '2p' /tmp/.auth)
export PASS=$(sed -n '3p' /tmp/.auth)

sudo docker login -u amit2328 -p $PASS
cd ~/maven && sudo docker-compose up -d